### ISSUE TITLE
Remove defaultBlockName

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-enter#25]
As we discussed with @Reinmar, it appeared that in most cases, using `EnterCommand` at the end of block element should create the same block. Right now, `EnterCommand` has `defaultBlockName` equal to `paragraph`. This was done with `Headings` in mind, but in fact headings are special case, not the other way around. For example, using `EnterCommand` at the end of `listItem` should create new list item.

`EnterCommand` should not have any `defaultBlockName` and should be able to take it as an execution parameter to enable special cases like headings.

**Comment by Reinmar** [comment]
Yeah, it turned out that it's only the heading feature where enter needs to behave this way. In lists or blockquotes it needs to continue the same type of element and in empty list items or empty paragraph in blockquotes it needs to change the current item which is one more behaviour to code. So I agree that we should better remove this param.

**Comment by scofalik** [comment]
After short discussion we decided that it will be good to move those algorithms to `engine.model.Composer`. After this is done, `EnterCommand` will just use `Composer`.
